In [8]:
import numpy as np
import ase
from ase.build import molecule
from ase.optimize import LBFGS

In [9]:
from qmlearn.api.api4ase import QMLCalculator
from qmlearn.drivers.mol import QMMol
from qmlearn.io.model import db2qmmodel

In [10]:
qmmodel = db2qmmodel('h2o_vib_QML_set.hdf5')

Guess DB names : {'qmmol': 'rks/qmmol', 'atoms': 'rks/train_atoms_36', 'properties': 'rks/train_props_36'}
Guess mmodels: {'gamma': KernelRidge(alpha=0.1), 'd_gamma': LinearRegression(), 'd_energy': LinearRegression(), 'd_forces': LinearRegression()}


In [11]:
second_learn = {
        'energy' : 'd_energy',
        'forces' : 'd_forces',
        }
calc = QMLCalculator(qmmodel = qmmodel, second_learn = second_learn, method = 'gamma')

In [12]:
atoms_test=molecule('H2O')
atoms_test.positions[0,0] += 0.2

In [13]:
atoms = atoms_test.copy()
atoms.calc = calc

In [14]:
LBFGS(atoms, trajectory = 'opt.traj').run(fmax=0.01)
atoms.positions

       Step     Time          Energy         fmax
LBFGS:    0 17:44:04    -2070.589750        1.2783
LBFGS:    1 17:44:04    -2070.613779        0.5374
LBFGS:    2 17:44:05    -2070.614010        0.5165
LBFGS:    3 17:44:05    -2070.618349        0.0467
LBFGS:    4 17:44:05    -2070.618366        0.0341
LBFGS:    5 17:44:05    -2070.618421        0.0119
LBFGS:    6 17:44:06    -2070.618417        0.0030


array([[ 1.99167916e-01, -3.47856762e-05,  9.49234377e-02],
       [ 4.17777201e-04,  7.65802839e-01, -4.64825182e-01],
       [ 4.14336067e-04, -7.65768131e-01, -4.64930179e-01]])

In [15]:
basis = 'cc-pvTZ'
xc = 'lda,vwn_rpa'
method = 'rks'
charge = 0

In [16]:
atoms = atoms_test.copy()
refqmmol = QMMol(atoms = atoms, method = method, basis=basis, xc = xc, charge=charge)
atoms.calc = QMLCalculator(qmmodel = refqmmol, method = 'engine')

In [17]:
LBFGS(atoms, trajectory = 'opt.traj').run(fmax=0.01)
atoms.positions

       Step     Time          Energy         fmax
LBFGS:    0 17:44:13    -2070.596525        1.3259
LBFGS:    1 17:44:17    -2070.616301        0.2563
LBFGS:    2 17:44:23    -2070.617393        0.1126
LBFGS:    3 17:44:29    -2070.618015        0.1030
LBFGS:    4 17:44:35    -2070.618396        0.0495
LBFGS:    5 17:44:40    -2070.618425        0.0106
LBFGS:    6 17:44:46    -2070.618427        0.0005


array([[ 1.92577545e-01,  3.29547777e-15,  9.72371798e-02],
       [ 3.71122733e-03,  7.65804799e-01, -4.66034590e-01],
       [ 3.71122733e-03, -7.65804799e-01, -4.66034590e-01]])

In [19]:
qmmodel = db2qmmodel('./h2o_md_300_QML_set.hdf5')
atoms = atoms_test.copy()
atoms.calc = QMLCalculator(qmmodel = qmmodel, second_learn = second_learn, method = 'gamma')
LBFGS(atoms, trajectory = 'opt.traj').run(fmax=0.01)
atoms.positions

Guess DB names : {'qmmol': 'rks/qmmol', 'atoms': 'rks/train_atoms_30', 'properties': 'rks/train_props_30'}
Guess mmodels: {'gamma': KernelRidge(alpha=0.1), 'd_gamma': LinearRegression(), 'd_energy': LinearRegression(), 'd_forces': LinearRegression()}
       Step     Time          Energy         fmax
LBFGS:    0 17:45:31    -2070.596523        1.3260
LBFGS:    1 17:45:31    -2070.616322        0.2564
LBFGS:    2 17:45:31    -2070.617412        0.1126
LBFGS:    3 17:45:32    -2070.618032        0.1029
LBFGS:    4 17:45:32    -2070.618411        0.0495
LBFGS:    5 17:45:32    -2070.618441        0.0106
LBFGS:    6 17:45:32    -2070.618441        0.0014


array([[ 1.92610265e-01,  1.14244173e-05,  9.72291730e-02],
       [ 3.69633877e-03,  7.65794139e-01, -4.66026200e-01],
       [ 3.69338994e-03, -7.65805574e-01, -4.66034992e-01]])

In [20]:
qmmodel